### PR TITLE
Add fping package

### PR DESCRIPTION
**Pull request by mayank-sirotiya-imgtec**
Signed-off-by: Mayank Sirotiya <Mayank.Sirotiya@imgtec.com>

### CODE REVIEW

**Comment by abhijit-mahajani-imgtec** [comment]
Approved

**Comment by nikhil-zinjurde-imgtec** [comment]
Update openwrt-feeds/README.md to include fping package information

**Comment by abhijit-mahajani-imgtec** [comment]
Approved and Verified

**Comment by nikhil-zinjurde-imgtec** [comment]
QA Verified

**Pull request merged**
